### ISSUE TITLE
Wrong window receives focus when screen is split in three

### ISSUE THREAD

**Issue by qadzek** [klangman/Adjacent-Windows#3]
I am using a single screen, and my window is split like this, using tiling: A occupies the left half of the screen, B the top-right quarter, and C the bottom-right quarter. There are no windows underneath.

```
AB
AC
```

When I use the 'Activate window below' hotkey while B is focused, the expected behavior is to move the focus to C. Instead, window A gets focused.

This bug is present when using the setting 'Closest with a visible corner' or 'Highest in the z-order'. It isn't present when using 'Closest to the current window'.

Hopefully, you can reproduce this. Screenshot: https://i.imgur.com/RHtOaa8.png

**Comment by klangman** [comment]
Oh... Ya, I broke something with my last update. I stopped checking all windows for overlapping the corners, instead I am only checking the windows that are candidates for the next window to switch focus to. I'll fix that tonight.

**Comment by klangman** [comment]
I was unable to recreate the problem, but I guess it's possible that I fixed it with one of today's changes before I started testing your scenario??
